version: 2
jobs:
  build:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      # - run: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"
      - run: ./hadoop-ozone/dev-support/checks/build.sh
  checkstyle:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      # - run: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"
      - run: ./hadoop-ozone/dev-support/checks/build.sh && ./hadoop-ozone/dev-support/checks/checkstyle.sh
      - store_artifacts:
          path: ./target/checkstyle/summary.txt
          destination: checkstyle
  rat:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      - run: ./hadoop-ozone/dev-support/checks/rat.sh
      - store_artifacts:
          path: ./target/rat/summary.txt
          destination: rat
  author:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      - run: ./hadoop-ozone/dev-support/checks/author.sh
  findbugs:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      - run: ./hadoop-ozone/dev-support/checks/findbugs.sh
      - store_artifacts:
          path: ./target/findbugs/summary.txt
          destination: findbugs
  unit:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      - run: ./hadoop-ozone/dev-support/checks/unit.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - store_artifacts:
          path: ./target/unit/summary.txt
          destination: unit
  acceptance:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: ./hadoop-ozone/dev-support/checks/acceptance.sh
      - store_artifacts:
         path: ./target/acceptance/summary.txt
         destination: acceptance
  integration:
    docker:
      - image: vivekratnavel/hadoop-ozone-build:v1
    steps:
      - checkout
      - run:
          command: ./hadoop-ozone/dev-support/checks/integration.sh
          no_output_timeout: 20m
      - store_artifacts:
          path: ./target/integration/summary.txt
          destination: integration
workflows:
  version: 2
  ci_run:
    jobs:
      - build
      - checkstyle
      - rat
      - author
      - findbugs:
          requires:
            - build
      - unit:
          requires:
            - build
      - acceptance